### ISSUE TITLE
Tap to toggle a star

### ISSUE THREAD

**Issue by wdavies973** [sarbagyastha/flutter_rating_bar#41] opened 2020-08-25 03:32 UTC
Is there a way to tap on a star to toggle whether its set or not? This is especially useful for toggling the first star, as its slightly intuitive for the user to swipe to the left on it.

**Comment by sarbagyastha** [comment] 2020-11-10 04:11
Duplicate of #33

**Closed by sarbagyastha** 2020-11-10 04:11 UTC
