### ISSUE TITLE
Error using first example in Readme

### ISSUE THREAD

**Issue by AriCohen8** [sarbagyastha/flutter_rating_bar#14] opened 2019-08-20 22:06 UTC
Hello, thank you for the package.

I get an error using your first example:
RatingBar(
   initialRating: 3,
   direction: Axis.horizontal,
   allowHalfRating: true,
   itemCount: 5,
   itemPadding: EdgeInsets.symmetric(horizontal: 4.0),
   itemBuilder: (context, _) => Icon(
     Icons.star,
     color: Colors.amber,
   ),
   onRatingUpdate: (rating) {
     print(rating);
   },
);

Error points to row 119 of the package claiming withAlpha is being called on null. When I put in the unratedcolor parameter it works. Not sure if this is to do with my usage or a bug in the plugin?

**Comment by sarbagyastha** [comment] 2019-08-21 00:33
Duplicate of #13 .

**Closed** 2019-08-21 05:26 UTC
